// svelte-hashmon/src/components/Notification.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  export let notification: { open: boolean; message: string; severity: 'success' | 'error' | 'info' | 'warning' };

  const dispatch = createEventDispatcher();

  const close = () => {
    dispatch('close');
  };
</script>

<!-- {#if notification.open} -->
<!--   <div class={`alert alert-${notification.severity} shadow-lg fixed top-5 right-5 z-50`}> -->
<!--     <div> -->
<!--       <span>{notification.message}</span> -->
<!--       <button class="btn btn-sm btn-ghost" on:click={close}>✕</button> -->
<!--     </div> -->
<!--   </div> -->
<!-- {/if} -->

// hashmon-frontend/src/components/Notification.tsx
import React from 'react';
import { Snackbar, Alert } from '@mui/material';

interface NotificationProps {
  open: boolean;
  message: string;
  severity: 'success' | 'error' | 'info' | 'warning';
  onClose: () => void;
}

const Notification: React.FC<NotificationProps> = ({ open, message, severity, onClose }) => {
  return (
    <Snackbar open={open} autoHideDuration={6000} onClose={onClose} anchorOrigin={{ vertical: 'top', horizontal: 'center' }}>
      <Alert onClose={onClose} severity={severity} sx={{ width: '100%' }}>
        {message}
      </Alert>
    </Snackbar>
  );
};

export default Notification;
